### PR TITLE
Let 609 fe add beta tag

### PR DESCRIPTION
**Pull request by barbara-chaves**
This PR adds the BETA tag to the HeCo header logo and the beta version disclaimer banner

## Description 
As an HeCo visitor, I can see that the platform is a beta version, so I am aware that certain functionalities will be limited, improving expectations

Acceptance criteria

There will be a way to indicate (all pages? only public?) that the platform is in its beta version

Add “beta” to logo as per LET-622

There will be a disclaimer indicating that certain functionalities are limited for the time being

Disclaimer: 

Without link to FAQ’s:“HeCo Invest is currently on Beta version. We are still testing and making improvements and for that reason some features may not be fully functional.” **--This one is being currently used --**

With link to FAQ’s: HeCo Invest is currently on Beta version. We are still testing and making improvements and for that reason some features may not be fully functional. About the Beta version

## Testing instructions

“HeCo” logo displays a “beta” word next to it  

There will be a disclaimer indicating that certain functionalities are limited for the time being

Respects the Figma [designs](https://www.figma.com/file/KC49uMR9t1YARmFR0Sr6aN/HeCo---Work-in-progress?node-id=6070%3A99397)

## Tracking

[LET-609](https://vizzuality.atlassian.net/browse/LET-609)

## Screenshot 
Screenshot 2022-07-15 at 16 00 05

### CODE REVIEW

**Comment by clementprdhomme** [comment]
@barbara-chaves I removed Simão and I as reviewers and added back the wip tag since we discussed today that the disclaimer needs to be updated. Add us back when you're ready for review.

**Comment by clementprdhomme** [comment]
@barbara-chaves I think we could make three further improvements.

**Beta tag background**
When the page is scrolled, the logo's beta tag should have a green background (see [here](https://www.figma.com/file/KC49uMR9t1YARmFR0Sr6aN/HeCo---Work-in-progress?node-id=2%3A3602)).
Next to the logo, the beta tag is white on a green background

**Disclaimer hidden by default**
When the disclaimer is dismissed, every time the user reloads the page, it appears briefly before disappearing again.

https://user-images.githubusercontent.com/6073968/179461593-c3905a9e-4101-4388-b6ba-0de14d1fa28c.mp4

You could fix this issue by making the disclaimer hidden by default and shown when the setting can't be found in the session storage.

**Use of local storage**
You use the session storage to store if the user has dismissed the disclaimer. This means that every time the user closes the browser and reopens it, the disclaimer will be shown again. I would instead use the local storage so it is never shown again if dismissed (unless the browser's cache is cleaned).

**Comment by clementprdhomme** [comment]
@barbara-chaves I pushed a small change to display the disclaimer at the bottom of the screen on mobile otherwise the navigation is not legible. Is that ok?

<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>The disclaimer pushes the navigation to the bottom, making it illegible</td>
<td>The disclaimer is fixed at the bottom of the screen</td>
</tr>
</table>

**Comment by barbara-chaves** [comment]
> @barbara-chaves I pushed a small change to display the disclaimer at the bottom of the screen on mobile otherwise the navigation is not legible. Is that ok?
> 
> Before	After
> The disclaimer pushes the navigation to the bottom, making it illegible	The disclaimer is fixed at the bottom of the screen

Ok! Perfect

**Pull request merged**
