### PR TITLE
Backend Configure rails app to deploy to subdirectory

### PR DESCRIPTION
**Pull request by tsubik**
I believe that we have to configure rails app to run in subdirectory

https://guides.rubyonrails.org/configuring.html#config-action-controller-relative-url-root
https://gist.github.com/ebeigarts/5450422

I would leave setting env variables in infrastructure to @tiagojsag 

## Testing instructions

Deploy and check if it works

## Tracking

No tracking

### CODE REVIEW

**Comment by tiagojsag** [comment]
you can add it here: https://github.com/Vizzuality/heco-invest/blob/9458713178e19b99555283d22f31406225506278/infrastructure/base/modules/env/main.tf#L126

Let me know once it's in place so I can deploy the change

**Comment by tsubik** [comment]
Ok. I think that will be needed in Dockerfile as well, as we have `assets:precompile` after adding backoffice.

**Comment by tsubik** [comment]
But maybe that should be added there when adding backoffice.

**Review by martintomas — APPROVED** [review]
Tried, works for me on my local machine.

**Review by agnessa — APPROVED** [review]

**Comment by tsubik** [comment]
@tiagojsag I think that is ready to deploy. Didn't change Dockerfile as we don't do assets:precompile for now.

**Pull request merged**
